[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration spécifique pour Next.js App Router
[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Pas de redirections custom pour laisser Next.js gérer
