[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Suppression de la règle de redirection qui causait le problème
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
